-- Generated by nwg-displays on 2026-09-25 at 21:48:33. Do not edit manually.

hl.monitor({
    output = "HDMI-A-2",
    mode = "3840x2160@240.0",
    position = "0x0",
    scale = 1.0,
    bitdepth = 10,
    vrr = 0
})
