-- Generated by nwg-displays on 2026-06-05 at 22:01:49. Do not edit manually.

hl.monitor({
    output = "HDMI-A-2",
    mode = "3840x2160@240.0",
    position = "0x0",
    scale = 1.2000000000000002,
    bitdepth = 10
})
