-- Generated by nwg-displays on 2026-07-09 at 19:33:32. Do not edit manually.

hl.monitor({
    output = "HDMI-A-2",
    mode = "3840x2160@240.0",
    position = "0x0",
    scale = 1.0,
    bitdepth = 10
})
